### ISSUE TITLE
Support for <Route ignore>

### ISSUE THREAD

**Issue by ronthecookie** [AlexxNB/tinro#11]
I have a link that goes to `/api/auth` and this request would usually go to the API but tinro catches that.
I'd like to be able to do this and I tried to make a PR but I don't understand the code very well yet:
```html
<Route path="/api/*" ignore />
```
## Alternative name
- `passthrough`

**Comment by AlexxNB** [comment]
The question is how to disable certain URLs in the `<a>` to be passed in tinro?

**Comment by AlexxNB** [comment]
I think it may be like this: `<a href="/api/auth" data-tinro-ignore>To API</a>`

**Comment by ronthecookie** [comment]
Yeah, that'd work too

**Comment by AlexxNB** [comment]
Ok, I'll implement it in future version.

**Comment by ronthecookie** [comment]
Awesome, thanks.
By the way, for now I just forked tinro and changed the regex to disallow /api

**Comment by AlexxNB** [comment]
Added in v.0.2.5
Read [here](https://www.npmjs.com/package/tinro#links) how to use it.

**Comment by ronthecookie** [comment]
Cool, thanks

**Comment by AlexxNB** [comment]
Please update to v.0.2.7. there was a bug when `tinro-ignore` attribute being removed after first click.
