### ISSUE TITLE
Lazy loading and params

### ISSUE THREAD

**Issue by aidarkhanov** [AlexxNB/tinro#15]
Hello, thank you once again for this library!

I have a weird problem with getting url params inside lazy loaded components.

Let's imagine we have a lazy component inside a route `<Route path="/:name"><Lazy component={...}></Route>`.

When I call `router.getParams()` method inside the component, I get an error:
`TypeError: (intermediate value).getParams is not a function`

[Here is the example](https://svelte.dev/repl/2af037ac8d3d409381746333b5c731af?version=3.22.3) I put up in REPL (for code overview) and a ready environment with the example: [svelte-app.zip](https://github.com/AlexxNB/tinro/files/4676937/svelte-app.zip)

**Comment by aidarkhanov** [comment]
I think I know what the problem is: Lazy component does not propagate params through the Route, so the workaround is to introduce a new param inside the `<Lazy />` component.

Something like this should work: `<Lazy component={...} {params} />`.

[Here is the working example](https://svelte.dev/repl/33f2bdc104544f14a353fb0ab0b44c0d?version=3.22.3)that fixes params propagation to lazy component. But this would introduce fiddling around with params leading to unnecessary redundancy.

Now, there is a trade-off: either include standard `<Lazy />` component in tinro but increasing the bundle size or have another design considerations to lazy loading.

**Comment by AlexxNB** [comment]
Thanks, good catch. But I just forgot to edit Readme when update tinro's API some time ago. Use `router.params()` instead `router.getParams()` =)

**Comment by aidarkhanov** [comment]
What?! Yeah, that was unexpected. Thanks!

**Comment by aidarkhanov** [comment]
For anyone looking for the proper example: https://svelte.dev/repl/2af037ac8d3d409381746333b5c731af?version=3.22.3
