### ISSUE TITLE
hash router not scroll on top on page change

### ISSUE THREAD

**Issue by az67128** [AlexxNB/tinro#16]
if page changed scroll remains as on previous page.
Hash router is used.

**Comment by AlexxNB** [comment]
There no any scroll manipulation due navigation. So you can use advice from [this issue](https://github.com/AlexxNB/tinro/issues/3#issuecomment-620520511) to scroll at the top of the page each time `$router.path changes`

**Comment by az67128** [comment]
Could you be so kind to add this solution to docs?

**Comment by AlexxNB** [comment]
Shure. Will do.
