### ISSUE TITLE
Nested redirects

### ISSUE THREAD

**Issue by jnordberg** [AlexxNB/tinro#18]
When in a nested route it would be handy to be able to redirect relative to the current nested route. Perhaps something like this?

```svelte
<Route>
    <Route path="/">
        <p>Root</p>
    </Route>
    <Route path="/sub/*">
        <!-- this would redirect to /sub/one instead of /one  -->
        <Route path="/" relative-redirect="/one" />
        <Route path="/one">One</Route>
        <Route path="/two">Two</Route>
    </Route>
</Route>
```

Alternatively a `redirect="one"` (without the leading slash) could be treated as relative

**Comment by AlexxNB** [comment]
implemented in v.0.2.0

**Comment by AlexxNB** [comment]
`<Route path="/sub/noaccess" redirect="subpage" />` will redirect to `/sub/noaccess`.
