### ISSUE TITLE
Can someone please explain the each block code for Recipes -> Transitions

### ISSUE THREAD

**Issue by kritollm** [AlexxNB/tinro#20]
`{#each '_' as _($router.path)}{$router.path,''}`

Hi. Can someone please explain the code above. Recipes -> Transitions

Sorry if this does not fall under issues, but I have googled and searched in the Svelte documentation without being able to get an understanding of how the code works.

**Comment by AlexxNB** [comment]
It is just a magic which I created when looking for a way to remount  template parts when some variable changes.
