### ISSUE TITLE
Is there a way to make router.params() reactive?

### ISSUE THREAD

**Issue by jamauro** [AlexxNB/tinro#21]
When navigating between routes that have the same shape, e.g. `/things/:id`, it doesn't appear that `router.params()` is updated. Is there a way to make it reactive?

If I go back to `/things` and navigate to another `/things/:id`, it works as expected.
If I pass in the param using the `let:params`, the `params.id` is updated as expected.

**Comment by AlexxNB** [comment]
You can use reactive statement:
```
$: params = router.params($router)
```
See example here - https://svelte.dev/repl/c711f397d4924ccda79224e8a3ee0ada?version=3.24.1
