### ISSUE TITLE
Typescript problem

### ISSUE THREAD

**Issue by meigo** [AlexxNB/tinro#23]
When using in typescript enabled components
```JSX
<script lang="ts">
  import { Route } from 'tinro';
  ...
</script>

<Route path="/">
  <h1>It is main page</h1>
</Route>
...
```
getting typescript complaints
```console
JSX element class does not support attributes because it does not have a '$$prop_def' property.ts(2607)
'Route' cannot be used as a JSX component.
  Its instance type 'Route' is not a valid JSX element.
    Property '$$prop_def' is missing in type 'Route' but required in type 'ElementClass'.ts(2786)
```
Other than that this router is wonderful little gem, thank you.

**Comment by AlexxNB** [comment]
Do you use latest version? Same issue was fixedsome time ago https://github.com/AlexxNB/tinro/issues/17

**Comment by meigo** [comment]
Yes, tinro@0.3.3 on svelte@3.24.1

**Comment by AlexxNB** [comment]
Could you try version 3.0.0 - there are previous version of type declarations, I wrote myself. Then they been rewrites by community.
Anyway I need help with manualy type definitions in `*.d.ts` file, because typescript is not my everyday tool.

**Comment by meigo** [comment]
Thanks, got better with v3.0.0 but still
```console
JSX element class does not support attributes because it does not have a '$$prop_def' property.ts(2607)
```

**Comment by AlexxNB** [comment]
Ok, I'll try to resolve this soon, if nobody helps.

**Comment by AlexxNB** [comment]
Check the 0.3.4 version - should be fine now.

**Comment by meigo** [comment]
Looks great now, thank you.

**Comment by AlexxNB** [comment]
Cool!
