### ISSUE TITLE
Refreshing a route gives 404

### ISSUE THREAD

**Issue by onderb** [AlexxNB/tinro#27]
As I mentioned in the title, the app doesn't navigate to desired page/route other than `/` if page is refreshed or navigated from address bar. I followed installation and usage documentation which is written in README.md here.

**Comment by AlexxNB** [comment]
Looks like you don't setup your server to support History API navigation, as described [here](https://www.npmjs.com/package/tinro#server-side-setup-for-history-api-method)

**Comment by onderb** [comment]
Thank you. The issue can be closed.
