### ISSUE TITLE
Fallback route showing in wildcard routes

### ISSUE THREAD

**Issue by guillemc** [AlexxNB/tinro#28]
In a structure like this:

```svelte
<Route>  <!-- same as <Route path="/*"> -->
    <Route path="/"><h1>It is main page</h1></Route>
    <Route path="/books/*">
        <Route path="/"><Index /></Route>
        <Route path="/fiction"><Page /></Route>
        <Route path="/drama"><Page /></Route>
    </Route>
    <Route fallback><NotFound /></Route>
</Route>
```

Loading route "/books" also triggers the NotFound component (see the console log in this [REPL](https://svelte.dev/repl/7b0dbb273165443ebe64a68f850e2c69?version=3.30.0)).

In the site I'm developing, the NotFound is also visible briefly as a flash of content...

Is this intentional? I hoped the fallback route to only be loaded if there was no match from any previous route.

**Comment by AlexxNB** [comment]
Will check it out. Thanks.

**Comment by AlexxNB** [comment]
Works fine in 0.4.1.

**Comment by guillemc** [comment]
Yep, thanks a lot!
