### ISSUE TITLE
Path parameters with lazy loading

### ISSUE THREAD

**Issue by ritchieanesco** [AlexxNB/tinro#35]
Hi guys,

Really great work with this library! Is it possible to use path parameters with lazy loading? I'm wondering how you would go about passing parameters as props to something lazy loaded.

**Comment by AlexxNB** [comment]
Here two ways to use params in Lazy loaded components:

https://svelte.dev/repl/77594e4f987b4f63a8c30aadaa9f6de4?version=3.31.0

**Comment by ritchieanesco** [comment]
Thanks @AlexxNB. Got it working with your example.
