### ISSUE TITLE
Browser back button doesn't work with `router.mode.hash()`

### ISSUE THREAD

**Issue by NfNitLoop** [AlexxNB/tinro#45]
I reported this in #42, but since the main issue is fixed, I'm re-reporting this as its own issue:

Without `router.mode.hash()`, I can:

* open a page
* click on a link
* The page updates and shows the `<Route>` content for that link.
* click the browser back button
* The previous page's contents are shown.

But, if I add `router.mode.hash()`, clicking the back button doesn't work. It *does* change the URL in the browser bar, but the contents rendered in the page do not revert to the original contents.  (Fully reloading the page fixes this.)

Should this work the same as the default router mode?

**Comment by AlexxNB** [comment]
fixed in 495e294e71491785bfdb7e733cf271707875e71f
