### ISSUE TITLE
Redirect to another route on fallback

### ISSUE THREAD

**Issue by DhyeyMoliya** [AlexxNB/tinro#49]
Can there be a functionality to redirect to another route on fallback condition (like `"/"` page or  `/404` something?).

I am asking because on fallback, the url stays the same and the content get rendered. But can we do something like redirect to `/404`.

```svelte
<Route path="/"> <Home /> </Route>
<Route fallback redirect="/">
```

**Comment by AlexxNB** [comment]
Thanks! This was a missed feature I added now
