### ISSUE TITLE
<a> link issues

### ISSUE THREAD

**Issue by sourcegr** [AlexxNB/tinro#50]
Hey Alex, great lib.

`<a target="_blank" ...` should open in new window

Clicking on any `<a href=....` while holding the `cmd` (or `ctrl` in widows) should open in new window.

Edit: Actually, if any modifier key is pressed while clicking on the link, then the `<a...>` should not be handled by the lib.

**Comment by AlexxNB** [comment]
Is this issue for local links (started from `/`-sign) only, right?

**Comment by sourcegr** [comment]
> Is this issue for local links (started from /-sign) only, right?

I believe so.

**Comment by AlexxNB** [comment]
Thanks, fixed in 0.5.10

**Comment by sourcegr** [comment]
@AlexxNB, `control` is used on windows, but in order to be usable on the mac, it should check for `metaKey` 
The modifier keys, do other stuff as well. Here is a (hopefully complete) list

- on MacOS the `alt` key saves the contents of the link
- on MacOS the `cmd` (meta) opens the link in a new window
- on Windows the `alt` key saves the contents of the link
- on Windows the `ctrl` key opens the link in a new window

I believe you should check for any modifier and cancel handling on any of them

Also: The `target` could be `target="_self"` meaning that the lib **should** be handled by the lib.


Hope this helps :)

**Comment by AlexxNB** [comment]
Ok, will check all cases you wrote

**Comment by AlexxNB** [comment]
I added `alt`, `ctrl`, `shift` and `meta` keys. 
FYI, `Ctrl+click` - open in new tab, `shift+click` - open in new window.
Thank you, again
