### ISSUE TITLE
Advanced matching

### ISSUE THREAD

**Issue by mustafa0x** [AlexxNB/tinro#52]
Is there anyway to match something like `/:id-:slug`? Or does it have to be `/:id/:slug`?

What would be the easiest way to achieve `/:id-:slug`?

**Comment by AlexxNB** [comment]
You may use param `/:idandslug`, then just split it inside the route like this:
```js
const meta = router.meta();
let id,slug;
`$:  [id,slug] = $meta.params.idandslug.split('-');
```

**Comment by mustafa0x** [comment]
Thank you, that's good enough.

**Comment by mustafa0x** [comment]
I'm finding myself needing regex match more often. Is there any chance regex support will be added at some point? Thanks.
