### ISSUE TITLE
Error 'Function called outside component initialization' when calling route.meta()

### ISSUE THREAD

**Issue by renatodantas** [AlexxNB/tinro#53]
First of all, congrats for this amazing component.

I'm trying to get route information through `route.meta()` function inside an Svelte's `onMount()`, but I'm getting the follow error message: ```Function called outside component initialization```

I just tried to use example at https://github.com/AlexxNB/tinro/#route-meta in a fresh app, but without success.

I've added an example in REPL to show the problem (it's the first page of Svelte quickstart template): https://svelte.dev/repl/9f8ca34b8aef4b6e88f1eb64c1eff27f?version=3.32.1

**PS.:** If I call `route.meta()` as is in the example, the message changes to `Cannot read property 'meta' of undefined`.

Anything I'm doing wrong? Or is it a bug?

**Comment by AlexxNB** [comment]
The `router.meta()` function must be called inside any `Route`. 

```svelte
------------Hello.svelte--------------
<script>
    import {router} from 'tinro';
    const meta = router.meta();
</script>

Hello, {$meta.params.name}!

--------------------------------------

--------------App.svelte--------------
<script>
    import {Route} from 'tinro';
    import Hello from './Hello.svelte'
 </script>
<Route path="/:name">
   <Hello/>
</Route>
--------------------------------------
```

**Comment by renatodantas** [comment]
That's it.
I was using a component outside an outer `Route`.

Thanks, @AlexxNB.

**Comment by OysterD3** [comment]
Hi @AlexxNB, I am having this issue now.
I am using `meta()` inside `Route`


I found an workaround which is
```svelte
<Route path="/cinemas" let:meta>
  <MovieCinemasPage {meta} />
</Route>
```
However, `router.goto()` doesn't work. It changed the URL path but didn't navigate the user.

**Comment by AlexxNB** [comment]
> However, router.goto() doesn't work. It changed the URL path but didn't navigate the user.

Can you provide minimal example in REPL with same behaviour?

**Comment by OysterD3** [comment]
Hi @AlexxNB,

Here you go https://svelte.dev/repl/6262d8e2f5654e24ba31df605f0e9b3a?version=3.35.0

**Comment by AlexxNB** [comment]
I'm download your example from REPL and just run `npm install && npm run dev`. Everything works as expected in FF and Chrome.

**Comment by OysterD3** [comment]
I have started a fresh project
I think the issue has something to do with [vite](https://github.com/vitejs/vite). The `router.goto` doesn't work for `vite: ^2.1.4`

Somehow I downgraded my monorepo project to 2.1.0, it doesn't work as well

**Comment by AlexxNB** [comment]
Do u use SvelteKit?

**Comment by AlexxNB** [comment]
How I can start new empty project with your set?

**Comment by OysterD3** [comment]
You may follow the steps [here](https://github.com/vitejs/vite/tree/main/packages/create-app)

**Comment by harvey-k** [comment]
@OysterD3

The solution mentioned [here](https://github.com/vitejs/vite/issues/2760#issuecomment-809552053) seemed to get ```router.goto``` working for me.  Example vite.config.js:

```javascript
export default defineConfig({ 
  optimizeDeps: {
    exclude: ['tinro']
  },
  plugins: [svelte()],
 ...
```

**Comment by OysterD3** [comment]
Thanks a lot! @harvey-k 
That works for me
