### ISSUE TITLE
Package Changelog

### ISSUE THREAD

**Issue by philipp-tailor** [AlexxNB/tinro#57]
Thank you for a small wonderful router with great docs. 👏🏼 

I've been using tinro for a while, and the only friction I've noticed has been keeping it up to date. That's largely because changes are not noted down anywhere. Every time I've been updating tinro I had to scroll over the list of source changes to understand whether adaptions in my projects were required.

Compare this:

![image](https://user-images.githubusercontent.com/47689073/111027807-dabbd800-83f2-11eb-9be4-103abcb09594.png)

To:

![image](https://user-images.githubusercontent.com/47689073/111027825-fde68780-83f2-11eb-89d6-8912f751a57b.png)

While this is no big deal, the absence of a changelog is the only place where the package is not best-in-class.

Possible solutions could be to add a `CHANGELOG.md`, or to use github releases. Either description could be generated manually or automatically - the latter being easier if a machine readable commit structure like conventional commits were being used.

I'd be happy to contribute to making it happen, if you deem this worth tackling.

**Comment by AlexxNB** [comment]
It is exactly the thing I was going to do this weekend =)

**Comment by AlexxNB** [comment]
I added the workflow to generate changelog from conventional commits. (...and started using such commits from now =))
So now I need to know how to edit messages of pushed commits to proper generating changelog for older versions

**Comment by philipp-tailor** [comment]
Re-writing all commit messages might be possible if you rebase the whole master history, changing all commit hashes. That sounds extremely scary!
Two less risky alternatives:
* Only have a changelog going forward, which has worked well enough. New and existing users will benefit.
* Create the changelog for the past by hand. I'd be open to contribute if you pick this option.

**Comment by AlexxNB** [comment]
Looks like the github action, which I use, will regenerate whole `CHANGELOG.md` from scratch each commit. So I don't know the way to merge it with manually created one.

**Comment by philipp-tailor** [comment]
Oh,ok. Then I'm sure everyone will be content with having one going forward. 🤷

**Comment by AlexxNB** [comment]
Ha, I tried few actions for changelog generating and there no any I like. One did strange things and I had to rebase repository. Looks like I'll write my own generator. So issue still will be open for a time.

**Comment by philipp-tailor** [comment]
I've seen these two tools being used for conventional commit version & changelog generation. They are not pre-built action, but CI tools easily integrated in github actions: [auto](https://github.com/intuit/auto), [semantic release](https://github.com/semantic-release/semantic-release); there's also [release please](https://github.com/googleapis/release-please), which works with release PRs.

**Comment by AlexxNB** [comment]
The problem is that there no releases  - only tags(if i didn't forget run `git push --tags`). 

Newermind,  my changelog generator is almost done. It will generate versions from commits like `0.0.0`(it is default when you run `npm version...`) and from tags. Respects conventional commits, but also may add other commits to the changelog. It will work as CLI tool or Github action.

![image](https://user-images.githubusercontent.com/10389013/111125560-c6a6e080-8582-11eb-94ef-7e5a1e9bbc60.png)
It is how it looks in terminal =)

**Comment by AlexxNB** [comment]
Finally the [CHANGELOG.md](https://github.com/AlexxNB/tinro/blob/master/CHANGELOG.md) is here! Checkout my new tool - [Chalogen](https://github.com/AlexxNB/chalogen).
