### ISSUE TITLE
Active class question

### ISSUE THREAD

**Issue by ymatuhin** [AlexxNB/tinro#59]
Is there any benefits of using `use:active active-class="myactive"` instead of `use:active="myactive"`?
Maybe it will be ok to completely remove  `active-class` attribute.
Nice router btw, gonna try it on.

https://svelte.dev/docs#use_action

**Comment by AlexxNB** [comment]
We have other relative attribute - `exact`. Because why the `active-class`  is also attribute. I like neither of: 
- `<a use:active={{class:'myactive', exact:true}} />`
- `<a use:active={['myactive',true]} />`
- `<a use:active={'myactive'} exact/>`

**Comment by ymatuhin** [comment]
Fair enough, thanks 👍
