### ISSUE TITLE
router.goto is not working with Vite

### ISSUE THREAD

**Issue by silentworks** [AlexxNB/tinro#62]
I have a project where I'm using router.goto and it seems there is an issue with Vite when using this, I don't get an error but the url in the browser changes but the actual page doesn't load. I have attached a video showing this in action and here is also a link to a repo with the same code. https://github.com/silentworks/tinro-vite-svelte-issue

https://user-images.githubusercontent.com/79497/114796217-f0207b00-9d7f-11eb-84fb-51c31909ea58.mp4

**Comment by AlexxNB** [comment]
Hello, try this https://github.com/AlexxNB/tinro/issues/53#issuecomment-811205387

**Comment by silentworks** [comment]
Yeah, this fixed it. This should probably be added to a troubleshooting section of the README.md.

**Comment by AlexxNB** [comment]
I'll research a problem deeper, maybe I will get what Vite "optimize" in tinro and avoid this.
