### ISSUE TITLE
hash routing seems to be broken

### ISSUE THREAD

**Issue by philippdormann** [AlexxNB/tinro#64]
Hi there 👋

This issue basically refers to #42 

### I'm using
- `tinro@0.6.1`
- the hash mode example from the docs (see code)

```
<script>
    import {Route,router} from 'tinro';
    router.mode.hash();
</script>

<!-- Link should point browser to '/#/page/subpage' -->
<a href="/page/subpage">Subpage</a>

<!-- content when URL is '/#/page/subpage' -->
<Route path="/page/subpage">Subpage content</Route>
```

### Expected
- clicking on the link, browser should point to `/#/page/subpage`
- `/#/page/subpage` should display "Subpage content"

### Actual
- clicking on the link, the browser redirects to `/page/subpage`
- `/#/page/subpage` does not display "Subpage content"
- `/page/subpage` does display "Subpage content"

Any help will be appreciated 😀 Thanks for your work!

**Comment by AlexxNB** [comment]
Do you use default template, or something based on Vite, like SvelteKit maybe?

**Comment by philippdormann** [comment]
Exactly!
Just found the solution [here](https://github.com/vitejs/vite/issues/2760#issuecomment-809552053) 👌

Thanks for your quick response and have a nice day!

**Comment by AlexxNB** [comment]
Cool. I added troubleshooting section in Readme with this problem.

**Comment by philippdormann** [comment]
great, thanks! 🤝
