### ISSUE TITLE
Copied links in hash mode don't have a #

### ISSUE THREAD

**Issue by gereleth** [AlexxNB/tinro#65]
I initialized an app from [svelte template](https://github.com/sveltejs/template), installed tinro and put the following into `App.svelte`:

```html
<script>
  import {Route, router} from 'tinro';
  router.mode.hash();
</script>
<nav>
  <a href="/">Index</a>
  <a href="/foo">Foo</a>
</nav>
<main>
  <Route path="/">Index</Route>
  <Route path="/foo">Foo</Route>
</main>
```
Clicking on navigation links works fine, and I see correct hash-based links in the address bar. 
However, if I right-click a link to Foo and copy link location then I get a url without #:
`http://localhost:5000/foo` instead of `http://localhost:5000/#/foo`.

So copying a link and pasting it into the address bar gives an error. Is there a way to make link copy-pasting work?

**Comment by AlexxNB** [comment]
You might write `href="/#/foo"` if you want to support ability to copy links.

**Comment by gereleth** [comment]
Ok, that works! Thanks for the help =).
