### ISSUE TITLE
Rewrite in Typescript

### ISSUE THREAD

**Issue by gitpubber** [AlexxNB/tinro#69]
So, tinro is written in javascript. Can it be completely rewritten in Typescript so that we get benefits of Typescript ?

while having types guarantee that external typescript applications working with this library will have types, rewriting this library in typescript guarantees that there will be less bugs if any do exist.

I hope this will happen.

Thanks in advance.

**Comment by AlexxNB** [comment]
Transpiled code has a bigger value than JS one. I never use Typescript for small libs.
