### ISSUE TITLE
Rendered together routes with parameters and chars

### ISSUE THREAD

**Issue by frederikhors** [AlexxNB/tinro#7]
Using this:

```svelte
<Route path="/player/new">
  <New />
</Route>
<Route path="/player/:playerID" let:params>
  <Show playerID={params.playerID} />
</Route>
```

or this:

```svelte
<Route path="/player/*">
  <Route path="/new">
    <New />
  </Route>
  <Route path="/:playerID" let:params>
    <Show playerID={params.playerID} />
  </Route>
</Route>
```

it renders `/player/new` and `/player/123` together.

### Expected

It should render `<New />` if I'm on `/player/new` and `<Show />` if I'm on `/player/*` (everything is not `/player/new`).

Am I wrong?

**Comment by AlexxNB** [comment]
"/player/new" and "/player/:playerID" are both exact pathes and should be shown both. You should use other logic in your URL like "/player/new" and "/player/get/:playerID" or "/players/new" and "/player/:playerID". It is more clear to understand not only for router but and for humans who will be read your code after you.

**Comment by frederikhors** [comment]
I agree.

I'm trying with this code:

```svelte
<!-- Teams.svelte -->

<Route path="todos/new">
  <New />
</Route>
<Route path="todo/:todoID" let:params>
  <Todo todoID={params.todoID} />
</Route>
```

but when I use these imports in `App.svelte`:

```svelte
<script>
  const Home = import('./Home.svelte')
  const Teams = import('./Teams.svelte')
</script>

<Route>
  <Route path="/">
    <Lazy component={Home} />
  </Route>
  <Route path="teams/*">
    <Lazy component={Teams} />
  </Route>
  <Route fallback>
    <Lazy component={import('./404.svelte')} />
  </Route>
</Route>
```

it renders on `/teams/todo/123` both the `<Todo />` and fallback component. **Why?**

Note I also tried with the code below: the same:

```svelte
<Route path="todos/*">
  <Route path="new">
    <New />
  </Route>
</Route>
<Route path="todo/*">
  <Route path=":todoID" let:params>
    <Todo todoID={params.todoID} />
  </Route>
</Route>
```

If I not use `import()`s it works good.

I tried to reproduce it on Codesandbox (here: https://codesandbox.io/s/tinro-nested-path-two-not-one-107kj) but CSB doesn't work with `import()`s.

**Comment by AlexxNB** [comment]
You can reproduce this in the REPL I think.

**Comment by frederikhors** [comment]
One moment.

**Comment by frederikhors** [comment]
Here we are: https://svelte.dev/repl/427e3be14358416488945dd29da5ee87?version=3.21.0 but strange things happening...

**Comment by frederikhors** [comment]
It is working although it opens new windows on each link. But locally it renders fallback and <Todo />.

**Comment by AlexxNB** [comment]
Yeah, you should use `/#/page` notation for Links in REPL. Because REPL has own handler for all links inside.

**Comment by frederikhors** [comment]
One moment.

**Comment by frederikhors** [comment]
Updated with `#` and it is working. I can assure you locally it doesn't.

**Comment by frederikhors** [comment]
One moment.

**Comment by frederikhors** [comment]
A gif(t) for you!

![123456](https://user-images.githubusercontent.com/41120635/80495566-60b06b00-8968-11ea-82b6-be026c7f2b8b.gif)

**Comment by frederikhors** [comment]
And the same on `/new` too obviously.

**Comment by AlexxNB** [comment]
Downloaded and run your example on localhost. The problem is when nested routes are in `<Lazy>` router can't figure out that the path is exists and show fallback, but when component loaded it shows it too. So no routes should be in dynamic imports(or fallback should be in same import too, and no root fallback), sorry.

**Comment by frederikhors** [comment]
You, genius, do you give up so easily?

There must be a way to solve it.

**Comment by AlexxNB** [comment]
Solving is adding feature of async routes in the tinro itself with all handlings. But as I wrote before it is not prioritize. You should use something like `yrv` if lazyloaded routes are must have thing in your project.

**Comment by frederikhors** [comment]
I am very sad now. 😢

**Comment by frederikhors** [comment]
@AlexxNB, I thought that maybe there is a solution.

If `tinro` is a Svelte Store and the problem is:

> when nested routes are in <Lazy> router can't figure out that the path is exists and show fallback

maybe in `<Lazy />` component we can use some "flag" to say `router` that the path exists!

### Example

```svelte
<script>
  export let component

  router.routeFound = true // <-- THIS ONE
</script>

{#await component}
  Loading...
{:then cmp}
  <svelte:component this={cmp.default} />
{/await}
```

In this case we can avoid the fallback rendering.

What do you think?

**Comment by frederikhors** [comment]
Is it an idea you can consider?

**Comment by AlexxNB** [comment]
Nope, router store is not why tinro works. It is just URL changing handler. 
You have only this choices at the moment:

1. Do not use `<Route>` inside lazyloaded component. Consider to change your architecture:

*Before:*
```html
<!-- Mypage.svelte -->
I'm the page
<Route path="/page1"><Lazy cmp={import('./Page1.svelte)}/></Route>
<Route path="/page2"><Lazy cmp={import('./Page2.svelte)}/></Route>

<!-- App.svelte -->
<Route>
    <Lazy cmp={import('./Mypage.svelte)}/>
</Route> 
```
*After:*
```html
<!-- Pageroot.svelte -->
I'm the page

<!-- Mypage.svelte -->
<Lazy cmp={import('./Pageroot.svelte)} />
<Route path="/page1"><Lazy cmp={import('./Page1.svelte)} /></Route>
<Route path="/page2"><Lazy cmp={import('./Page2.svelte)} /></Route>

<!-- App.svelte -->
<Route>
    <Mypage />
</Route> 
```

2. Choose different router from the [list](https://svelte-community.netlify.com/code?tag=routers).
