### ISSUE TITLE
Reactive router behaviour

### ISSUE THREAD

**Issue by ieow** [AlexxNB/tinro#74]
Hi, I note that the reactive $router in the Book component does not update for Book in the route '/*' but do update for the Book in the path "/:genre/:author" when there is path changes.

I was expecting that the reactive router is updated on path changes like writable. 
```
<Route path="/*" >
  <Route path="/:genre/:author"><Book/></Route>
  <Book />
</Route>
```
->repl
https://svelte.dev/repl/2f6c12f28940451fb36e27ae9615f659?version=3.38.3

Which is the correct behavior?

**Comment by ieow** [comment]
I tried the announcer examples, it works fine

**Comment by AlexxNB** [comment]
`router.params` are deprecated many versions ago(did I leave any example which use it somewhere in readme?).
It was replaced with `meta.params` because params are unic for each Route, according it's path pattern. https://github.com/AlexxNB/tinro#metaparams

**Comment by ieow** [comment]
I was checking the example in the issue #21 
Did not notice it was deprecated.
Thanks!

**Comment by AlexxNB** [comment]
It will warn you, when you try to use it in IDE =)
![image](https://user-images.githubusercontent.com/10389013/123505495-13ad4f00-d668-11eb-95c5-e4548bd83b6c.png)

**Comment by ieow** [comment]
I was testing with repl. 
Yupe, I tried in IDE just now, and it did warn me.
