### ISSUE TITLE
Show sub navigation based on path 

### ISSUE THREAD

**Issue by cbaarendse** [AlexxNB/tinro#79]
Love this router. It looks like it will be easy to understand what is happening even months after coding. 

I'm looking to put a *sub-navigation bar* in my header, right under the *main-navigation*. The content of the sub-navigation depends on which part of the site one visits. One solution could be to base the choice for the right sub-navigation bar on an item on the router object. 

So for instance in the [Svelte REPL example](https://svelte.dev/repl/4bc37ff40ada4111b71fe292a4eb90f6?version=3.42.1). The sub navigation bar *Sites Photos* is now in the portfolio component. I would like it straight under the main nav bar *Home Portfolio Contacts*. Code would be something like:

```html
<header>
<nav class="main-nav"> ...</nav>
{#if $router.url =='/portfolio/*'} 
<nav class="sub-nav"> 
<a href='portfolio/sites'>Sites</a><a href='portfolio/photos'>Photos</a>
</nav>
{/if}
</header>
```
Then we could add other sub-navigation:
```html
{#if $router.url =='/contacts/*'} 
<nav class="sub-nav"> 
<a href='portfolio/address'>Adress</a><a href='portfolio/socialmedia'>Social Media</a>
</nav>
{/if}
```

or $router.base instead of $router.url, for instance:
```html
<{#if $router.base =='/portfolio'} 
<nav class="sub-nav"> 
<a href='portfolio/sites'>Sites</a> <a href='portfolio/photos'>Photos</a>
</nav>
{/if}
```

**Comment by AlexxNB** [comment]
Hello! So what is a question? Do you want to have `$router.base`? This is not a solution, because somebody may want to have 2nd level navigation, for example.

You can use `$router.path` to have current URL and check it for your needs:
```svelte
{#if $router.path.startsWith('/portfolio')}
...
{/if}
```

**Comment by cbaarendse** [comment]
Yes, that was the question. I will go with your solution nevertheless. That will keep it tiny. 🙂

Thank you,


Best,


Constantijn Baarendse
________________________________
