### ISSUE TITLE
Use:active isn't working with query params

### ISSUE THREAD

**Issue by jamauro** [AlexxNB/tinro#85]
Thanks for the router. It's been great.

I'm trying to leverage `use:active`. When I have query params e.g. `/something?q=test`, the active class isn't being applied.

Here's a quick example: https://svelte.dev/repl/c1ffe8a68ce941ab93c1ab60e5b329f9?version=3.42.1

I would expect `Contacts` in the main nav to be bolded. Am I missing something?

**Comment by Prinzhorn** [comment]
But is here

https://github.com/AlexxNB/tinro/blob/b4d3c0c8632d90b510f42f08124ee3f56d6dd609/src/router.js#L37

This needs to use `node.pathname` and not access the full attribute.

**Comment by AlexxNB** [comment]
Thanks, I will fix it

**Comment by AlexxNB** [comment]
closed in ddb222868da9a26376319c835763eab2deb6aa45
