### ISSUE TITLE
Support for guarded routes

### ISSUE THREAD

**Issue by aidarkhanov** [AlexxNB/tinro#9]
Hello, just saying this project is awesome!

However, I do have a question. Is there a best practice to guard routes, e.g. handling auth case? For example, it seems that React Router encourages imperative approach to guards leveraging a `Switch` component: [(stackoverflow link)](https://stackoverflow.com/questions/31084779/how-to-restrict-access-to-routes-in-react-router).

At the moment, I see only one approach to implement guards in tinro:

```svelte
{#if $isAuthenticated}
  <Route path="/enter">Authenticated!</Router>
{:else}
  <Route path="/noenter" redirect="/newurl"/>
{/if}
```

Also, I would like to help expanding the documentation with such a case, thanks!

**Comment by AlexxNB** [comment]
Thanks!
`Switch` in React looks boilerplaty.  Your `if` statement looks more declarative, and I like it. 

Also it is simple to make the guard-component like I did here: https://svelte.dev/repl/5673ff403af14411b0cd1785be3d996f?version=3.21.0

> Also, I would like to help expanding the documentation with such a case, thanks!

Be free for PR. I think it is good case for [Recipes](https://github.com/AlexxNB/tinro#recipes) section.

**Comment by aidarkhanov** [comment]
Cool idea! Let me see how the guard component works in order to write about it.

**Comment by AlexxNB** [comment]
I realy love just `{#if}` statement, my `<Guard/>` example is only to be like React =)

This look more declarative, as I think.
```html 
{#if $user}
	<Route path="/login/*" redirect="/profile"/>
	<Route path="/profile"><h1>It is User's profile page</h1></Route>
{:else}	
	<Route path="/profile/*" redirect="/login"/>
	<Route path="/login">
		<h1>Please sign in</h1>
		<button on:click={()=>$user=true}>Sign In</button>
	</Route>
{/if}
```

**Comment by AlexxNB** [comment]
I rewrite my example to with `<Authguard>` component

**Comment by aidarkhanov** [comment]
As I'm working on the routing in my project, I have noticed an issue, when `div[slot="not_authed"]` constantly appears on every page.

As `<svelte:fragment />` is being worked on, one solution can be [svelte-fragment](https://github.com/qutran/svelte-fragment) package with this [fix](https://github.com/qutran/svelte-fragment/pull/2), which I use.

**Comment by AlexxNB** [comment]
> As I'm working on the routing in my project, I have noticed an issue, when empty div[slot="not_authed"] container constantly appears on every page.

Can you reproduce this in REPL?

**Comment by aidarkhanov** [comment]
> 
> 
> > As I'm working on the routing in my project, I have noticed an issue, when empty div[slot="not_authed"] container constantly appears on every page.
> 
> Can you reproduce this in REPL?

This behavior is clearly presented in your example: https://svelte.dev/repl/5673ff403af14411b0cd1785be3d996f?version=3.21.0

Now, this is not tinro's problem, but rather Svelte's slot behavior.

![image](https://user-images.githubusercontent.com/36963426/81058068-7e914900-8eef-11ea-86c0-8d07694605fe.png)

![image](https://user-images.githubusercontent.com/36963426/81058088-8bae3800-8eef-11ea-9ae9-f0899d9038f0.png)

**Comment by aidarkhanov** [comment]
Sorry, had to delete the example using actions. Fragment action do not work as general-purpose solution, because it eagerly runs outside the constraints.

At the moment, `div[slot="not_authed"]` works well.

**Comment by AlexxNB** [comment]
Added info in readme myself =)
