### ISSUE TITLE
Typescript error with using exact on active classes on anchor element

### ISSUE THREAD

**Issue by saikatdas0790** [AlexxNB/tinro#96]
When I use the `active` action with the `exact` keyword on anchor tags in a Svelte + Typescript project, I get the following error. Is there a way to resolve the type error?
![image](https://user-images.githubusercontent.com/7412443/139536231-2216af72-5730-4153-8b8a-5cc82f5cb10f.png)

**Comment by AlexxNB** [comment]
try `data-exact` attribute

**Comment by saikatdas0790** [comment]
`data-exact` makes the error go away. Should we update the docs?

**Comment by AlexxNB** [comment]
`data-*` attributes for links are documented already:
![изображение](https://user-images.githubusercontent.com/10389013/141502885-40fba1bf-b958-4778-9211-9d781605cebf.png)
