### ISSUE TITLE
Link anchor to another section in the same page.

### ISSUE THREAD

**Issue by tuing2ing** [AlexxNB/tinro#99]
Hello, I am trying to implement this repl:
https://svelte.dev/repl/7006d7890b964928b8f72622a3d067ac?version=3.42.5
or similarly this codepen:
https://codepen.io/bramus/pen/ExaEqMJ

but once I add 
`import { router } from 'tinro/cmp/index.js';`

the link like this one
`<a href="#request-response">Request &amp; Response</a>`
stops working.

Is linking to the same page possible ?

**Comment by AlexxNB** [comment]
Looks like a bug. I'll check it.
